In [1]:
# python list 이용
a = [1, 2, 3]
b = [4, 5, 6]

num = [a, b]
print(num, type(num))

[[1, 2, 3], [4, 5, 6]] <class 'list'>


In [2]:
a+b

[1, 2, 3, 4, 5, 6]

In [3]:
num2 = list()
for idx in range(3):
    num2.append(a[idx] + b[idx])

print(num2, type(num2))

[5, 7, 9] <class 'list'>


In [6]:
# Numpy 배열
# Numpy 베열을 생성하는 방법 : list를 이용, Numpy 함수
import numpy as np
num1 = np.array(a)
num2 = np.array(b)

num = np.array([num1, num2])
print(num)
num1 + num2

[[1 2 3]
 [4 5 6]]


array([5, 7, 9])

In [9]:
# numpy 주요함수 : zeros(), ones(), full(), eye()
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [10]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
c = np.full((2,3), 5)
print(c)

[[5 5 5]
 [5 5 5]]


In [12]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
e = np.array(range(20)).reshape(4, 5)
print(e)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [20]:
# Numpy Slicing
a=[[1,2,3],[4,5,6],[7,8,9]]

In [21]:
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
c = b[0:2, 0:2]
print(c)

[[1 2]
 [4 5]]


In [23]:
a = [1,2,3,4,5]
arr = np.array(a)
print(arr)

[1 2 3 4 5]


In [25]:
# numpy는 열보다 행이 우선이다
arr.shape


(5,)

In [26]:
# 2차원 리스트
data2 = [[1,2,3],[4,5,6,]]
print(data2)

[[1, 2, 3], [4, 5, 6]]


In [28]:
# 92차원부터는 그대로 간다.
arr2 = np.array(data2)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [30]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [31]:
arr1 + arr2

array([[ 8, 10, 12],
       [14, 16, 18]])

In [32]:
arr1-arr2

array([[-6, -6, -6],
       [-6, -6, -6]])

In [33]:
arr1*arr2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [34]:
arr1/arr2

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [36]:
# String 배열
names = np.array(['홍길동', '장보고', '이순신', '강감찬', '임꺽정'])
print(names)

['홍길동' '장보고' '이순신' '강감찬' '임꺽정']


In [37]:
data = np.random.randn(7,4)
data

array([[ 0.73945752,  0.0773915 , -2.77629504, -0.81688066],
       [-0.87531275,  0.45735061,  2.36077303, -1.33888846],
       [-0.31799114,  1.46366808,  0.10027364,  0.48716852],
       [ 1.28826383,  0.32630601,  0.51534264,  0.89872625],
       [-1.60659845,  0.00343281, -0.41609935, -0.51239688],
       [-0.56114699, -1.14752373, -0.90997692,  1.39551559],
       [ 0.92329376,  0.09356386, -0.49917083,  1.40241901]])

In [39]:
x=np.random.randn(8)
y=np.random.randn(8)
print(x)
print(y)

[-0.54265051  1.16270904  0.37277635  1.56115851  1.29828789 -1.96594779
  0.6777251   0.55171023]
[ 0.93594614  1.76875456  0.32737973 -0.49662484  0.16092232 -1.48904697
 -1.09709958 -0.16528621]


In [40]:
# x,y중 큰 값을 선택하여 새로운 배열 생성
np.maximum(x, y)

array([ 0.93594614,  1.76875456,  0.37277635,  1.56115851,  1.29828789,
       -1.48904697,  0.6777251 ,  0.55171023])

In [41]:
# 5행 4열의 numpy 배열
arr1 = np.random.randn(5,4)
arr1

array([[ 0.16320463, -0.57872039, -0.48152736,  0.26514175],
       [ 1.8208686 ,  1.00489202, -0.05349424,  1.83554702],
       [ 0.17367384, -0.53194298, -0.30891531,  2.46764995],
       [ 1.03701187, -0.27483146,  0.53052409,  0.77392637],
       [-2.01678786, -0.50384878, -2.15201512,  1.48043881]])

In [42]:
#평균
arr1.mean()

0.23253977155647626

In [43]:
# 배열의 열 합계
arr1.sum(axis=0)

array([ 1.17797107, -0.88445159, -2.46542795,  6.8227039 ])

In [44]:
# 배열의 행 합계
arr1.sum(axis=1)

array([-0.63190138,  4.6078134 ,  1.8004655 ,  2.06663087, -3.19221296])

In [46]:
# 오름차순 정렬
arr1.sort()

array([[-0.57872039, -0.48152736,  0.16320463,  0.26514175],
       [-0.05349424,  1.00489202,  1.8208686 ,  1.83554702],
       [-0.53194298, -0.30891531,  0.17367384,  2.46764995],
       [-0.27483146,  0.53052409,  0.77392637,  1.03701187],
       [-2.15201512, -2.01678786, -0.50384878,  1.48043881]])

In [49]:
# https://grouplens.org/datasets/movielens/
# 영화평점 데이터셋 로딩
data = np.loadtxt('C:/python_workspace/data/movie/ml-1m/ratings.dat', delimiter='::', dtype=np.int64)

In [51]:
#넘파이 배열(행범위, 열범위)
#[start:end, start:end]
data[:5,:]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291]], dtype=int64)

In [52]:
data[100:110, :2]

array([[   2, 3654],
       [   2, 2852],
       [   2, 1945],
       [   2,  982],
       [   2, 1873],
       [   2, 2858],
       [   2, 1225],
       [   2, 2028],
       [   2,  515],
       [   2,  442]], dtype=int64)

In [53]:
data.shape

(1000209, 4)

In [54]:
# 전체 평점의 평균을 계산하시오
# total_mean = 전체행의 평점열.mean()
total_mean = data[:,2].mean()
total_mean

3.581564453029317

In [57]:
# 중복을 제거하고 고유값을 추출 : unique()
# data[행, 열]
# data[시작행: 마지막행, 시작열:마지막열]
user_ids = np.unique(data[:,0])
user_ids

array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64)

In [61]:
# 0번째열 : 사용자 id
# 사용자별 평점 평균
mean_value = []
for user_id in user_ids:
    # 반복문을 통해 얻은 사용자 아이디와 일치하는 아이디의 평점만 추출
    data_for_user = data[data[:,0] == user_id, :]
    # 평점의 평균을 계산한다.
    value = data_for_user[:, 2].mean()
    # 전체 고객의 평균평점을 담을 list에 추가하는 작업
    mean_value.append([user_id, value])

In [63]:
print(mean_value[:5])

[[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466]]
